Repository yohanym95/Food-Go, pull requests merged in 2020-10, with the labels that each got.

#3 Create splash screen
  assests/img/epic.png
  assests/img/foodgo.png
  lib/main.dart
  lib/pages/home.dart
  lib/pages/splash.dart
  lib/views/foodcart.dart
  pubspec.yaml
Labels: hacktoberfest, hacktoberfest-accepted

#4 add more photo
  assests/img/logo food go.jpg
Labels: hacktoberfest, hacktoberfest-accepted

#5 edited read me
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#6 2 stage
  README.md
  assests/img/logo food go.jpg
  lib/pages/splash.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
